### ISSUE TITLE
 rename and modify the code of `isFunction` to `isCallable` and bugfix

### ISSUE THREAD

**Issue by tst2005** [Positive07/obey#6]
Also a minor bugfix 

There should be a side effect in `return isFunction(result) and result() or result`

Sample of test :
```lua
local result = function() print("called") return false end
local isFunction = function(result) return true end

return isFunction(result) and result() or result
```
* call the function (and print "called")
* return the function value (`function: 0x123456`)

Supposed expected result:
* call the function (and print "called")
* return `false` (the function returned value)

```lua
local result = function() print("called") return false end
local isFunction = function(result) return true end

if isFunction(result) then
  return result()
end
return result
```

**Comment by pablomayobre** [comment]
Yeah, sounds right! Feel free to PR (I saw you have a draft already in place)
